[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T %v"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[hostname]
# ssh_only = false
ssh_only = true
format =  "@ [$hostname](bold red) "
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true
